version: '3.7'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - db

  backend:
    container_name: backend
    build: ./backend/testevktech
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - db
    depends_on:
      - db

networks:
  db:
    driver: bridge
